config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :users
  resources :questions
  post 'answers/create' => 'answers#create'
  post 'categories/create' => 'categories#create'
  get 'categories/aerospace'
  get 'categories/biomedical'
  get 'categories/chemical'
  get 'categories/civil'
  get 'categories/compeng'
  get 'categories/compsci'
  get 'categories/electrical'
  get 'categories/engsci'
  get 'categories/mechanical'
  get 'categories/systems'
  get 'categories/sts'
  get 'categories/esc'
  get 'categories/thetatau'
  get 'categories/ulink'
  get 'categories/swe'

  get 'questions/index'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'categories' => 'static_pages#categories'
  post 'questions', :to => 'categories#create'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if !current_user.nil?
      redirect_to categories_path
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def categories
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  UVA Forum was created by Various Artists to increase interaction between the UVA community...
</p>
</html>

app/views/static_pages/categories.html.erb
<% provide(:title, 'Categories') %>
<h1>Majors</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h4> <%= link_to("Aerospace Engineering", categories_aerospace_path) %> </h4>
      <h4> <%= link_to("Biomedical Engineering", categories_biomedical_path) %> </h4>
      <h4> <%= link_to("Chemical Engineering", categories_chemical_path) %> </h4>
      <h4> <%= link_to("Civil Engineering", categories_civil_path) %> </h4>
    </div>
    <div class="col-sm-4">
      <h4> <%= link_to("Computer Engineering", categories_compeng_path) %> </h4>
      <h4> <%= link_to("Computer Science", categories_compsci_path) %> </h4>
      <h4> <%= link_to("Electrical Engineering", categories_electrical_path) %> </h4>
    </div>
    <div class="col-sm-4">
      <h4> <%= link_to("Engineering Science", categories_engsci_path) %> </h4>
      <h4> <%= link_to("Mechanical Engineering", categories_mechanical_path) %> </h4>
      <h4> <%= link_to("Systems Engineering", categories_systems_path) %> </h4>
    </div>
  </div>
</div>
<h1>CIOs</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h4> <%= link_to("Engineering Student Council", categories_esc_path) %> </h4>
      <h4> <%= link_to("ULink", categories_ulink_path) %> </h4>
    </div>
    <div class="col-sm-4">
      <h4> <%= link_to("Society of Women Engineers", categories_swe_path) %> </h4>
    </div>
    <div class="col-sm-4">
      <h4> <%= link_to("Theta Tau", categories_thetatau_path) %> </h4>
    </div>
  </div>
</div>
<br>
<h3> <b> <center> <%= link_to("STS 2500 Projects", categories_sts_path, {style: "color: blue"}) %> </center> </b> </h3>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the UVA Forum</h1>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("uva.jpg", alt: "Rails logo"),
	class: "img" %>