config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :users
  resources :questions
  post 'answers/create' => 'answers#create'
  post 'categories/create' => 'categories#create'
  get 'categories/aerospace'
  get 'categories/biomedical'
  get 'categories/chemical'
  get 'categories/civil'
  get 'categories/compeng'
  get 'categories/compsci'
  get 'categories/electrical'
  get 'categories/engsci'
  get 'categories/mechanical'
  get 'categories/systems'
  get 'categories/sts'
  get 'categories/esc'
  get 'categories/thetatau'
  get 'categories/ulink'
  get 'categories/swe'

  get 'questions/index'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'categories' => 'static_pages#categories'
  post 'questions', :to => 'categories#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :questions
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  
  def aerospace
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "aerospace")
  end

  def biomedical
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "biomedical")
  end

  def chemical
    @answer = Answer.new
  	@question = Question.new
    @questions = Question.where(category: "chemical")
  end

  def civil
    @answer = Answer.new
  	@question = Question.new
    @questions = Question.where(category: "civil")
  end

  def compeng
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "compeng")
  end

  def compsci
    @answer = Answer.new
  	@question = Question.new
    @questions = Question.where(category: "compsci")
  end

  def electrical
    @answer = Answer.new
  	@question = Question.new
    @questions = Question.where(category: "electrical")
  end

  def engsci
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "engsci")
  end

  def mechanical
    @answer = Answer.new
  	@question = Question.new
    @questions = Question.where(category: "mechanical")
  end

  def systems
    @answer = Answer.new
  	@question = Question.new
    @questions = Question.where(category: "systems")
  end

  def sts
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "sts")
  end

  def esc
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "esc")
  end

  def swe
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "swe")
  end

  def thetatau
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "thetatau")
  end

  def ulink
    @answer = Answer.new
    @question = Question.new
    @questions = Question.where(category: "ulink")
  end
  
  def create
    @question = Question.new
    @question[:content] = params[:question][:content]
    @question[:category] = params[:category]
    @question[:user_id] = current_user[:id]
    if @question.save
      redirect_to :controller => 'categories', :action => params[:category]
    end
  end
  
  private
  
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/aerospace.html.erb
<h1>Aerospace Engineering</h1>
<h4>Ask any question regarding the Aerospace Engineering major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "aerospace")) do |f| %>
  <div class="row" style="overflow: hidden;">
    <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
    <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
  </div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/biomedical.html.erb
<h1>Biomedical Engineering</h1>
<h4>Ask any question regarding the Biomedical Engineering major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "biomedical")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/chemical.html.erb
<h1>Chemical Engineering</h1>
<h4>Ask any question regarding the Chemical Engineering major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "chemical")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/civil.html.erb
<h1>Civil Engineering</h1>
<h4>Ask any question regarding the Civil Engineering major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "civil")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/compsci.html.erb
<h1>Computer Science</h1>
<h4>Ask any question regarding the Computer Science major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "compsci")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/electrical.html.erb
<h1>Electrical Engineering</h1>
<h4>Ask any question regarding the Electrical Engineering major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "electrical")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/engsci.html.erb
<h1>Engineering Science</h1>
<h4>Ask any question regarding the Engineering Science major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "engsci")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/esc.html.erb
<h1><b><font color="black"> Engineering Student Council </font></b></h1>
<h3>About Us</h3>
<p>Engineering Student Council (ESC) is a Special Status Organization of the University of Virginia and the representative body for undergraduate students of the School of Engineering and Applied Science (SEAS). ESC provides a cohesive voice for the school’s undergraduate student body. The members of the council are entrusted with maintaining concern for SEAS students’ opinions and needs. </p>

<p>ESC members engage in direct and regular communication with the SEAS administration and faculty. Members serve on administrative and faculty committees and collaborate with Professors and Administrators in the planning and execution of events and programs. Throughout, the council serves as a learning experience, providing opportunities for increased responsibilities and professional development. </p>

<br>

<h4>Ask any question about the Engineering Student Council here!</h4>

<%= form_for(@question, url: categories_create_path(category: "esc")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/mechanical.html.erb
<h1>Mechanical Engineering</h1>
<h4>Ask any question regarding the Mechanical Engineering major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "mechanical")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/swe.html.erb
<h1><b><font color="black"> Society of Women Engineers </font></b></h1>
<h3>About Us</h3>
<p>The Society of Women Engineers is a professional organization that aims to support and promote women in achieving their full potential in engineering careers. The SWE section at UVA has three areas of focus: outreach, professional development, and community building. </p>

<p>SWE at UVA has outreach programs for girls at the elementary, middle, and high school levels, all of which aim to inspire interest in engineering fields through hands-on activities, design challenges, tours, and speakers. </p>

<p>We support the professional development of our members through a variety of events including interviewing workshops, resume reviews, major advising, company information sessions, and the national and regional SWE conferences. </p>

<p>We aim to foster a strong sense of community for our members through our mentorship family program, which encourages involvement and cross-class interaction. Additionally, we host many fun social events throughout the year, including pumpkin painting, apple picking, hiking, and stress-busting exercise classes. These events provide opportunities for our members to get to know each other and encourage collaboration in an environment beyond the classroom. </p>

<br>

<h4>Ask any question about the Society of Women Engineers here!</h4>

<%= form_for(@question, url: categories_create_path(category: "swe")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/systems.html.erb
<h1>Systems Engineering</h1>
<h4>Ask any question regarding the Systems Engineering major here!</h4>

<%= form_for(@question, url: categories_create_path(category: "systems")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/thetatau.html.erb
<h1><b><font color="black"> Theta Tau </font> </b> </h1>
<h3>About Us</h3>
<p>The purpose of Theta Tau is to develop and maintain a high standard of professional interest among its members, and to unite them in a strong bond of fraternal fellowship. Theta Tau is the oldest and largest professional engineering fraternity in the United States, with a diverse membership of men and women studying engineering at more than 40 campuses.</p>

<br>

<h4>Ask any question about Theta Tau here!</h4>

<%= form_for(@question, url: categories_create_path(category: "thetatau")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 

app/views/categories/ulink.html.erb
<h1><b><font color="black"> ULink </font></b></h1>
<h3>About Us</h3>
<p>ULink is an academic peer advising program run through U.Va.'s Student Council. ULink aims to match first years with upperclassmen peer advisors to discussclass and major choices, academic resources, and students' academic paths at the University. Students meet with their academic advisor throughout their first year, especially at important junctures such as class selection. </p>

<p>For organizations and student groups that already have advising programs, ULink may serve as an optional supplement, or complement, for the student. The program does not replace these specialized advising programs and will operate with and develop partnerships with such programs. </p>

<br>

<h4>Ask any question about ULink here!</h4>

<%= form_for(@question, url: categories_create_path(category: "ulink")) do |f| %>
<div class="row" style="overflow: hidden;">
  <%= f.text_field :content, :class=>"flexQuestions col-md-10" %>
  <%= f.submit "Ask!", class:"flexQuestions btn btn-primary col-md-2" %>
</div>
<% end %>

<% if !@questions.nil? %>
  <div>
    <u1 class="questions">
      <% @pullAnswers = true %>
      <%= render @questions %>
    </u1>
  </div>
<% end %> 